# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib rusterize, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_rusterize__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_rusterize__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


`rusterize_r` <- function(`geometry`, `raw_raster_info`, `rpixel_fn`, `rbackground`, `all_touched`, `encoding`, `dtype`, `rfield` = NULL, `rby` = NULL, `rburn` = NULL) {
  .savvy_wrap_RArray(.Call(savvy_rusterize_r__impl, `geometry`, `raw_raster_info`, `rpixel_fn`, `rbackground`, `all_touched`, `encoding`, `dtype`, `rfield`, `rby`, `rburn`))
}

### wrapper functions for RArray

`RArray_epsg` <- function(self) {
  function() {
    .Call(savvy_RArray_epsg__impl, `self`)
  }
}

`RArray_extent` <- function(self) {
  function() {
    .Call(savvy_RArray_extent__impl, `self`)
  }
}

`RArray_names` <- function(self) {
  function() {
    .Call(savvy_RArray_names__impl, `self`)
  }
}

`RArray_resolution` <- function(self) {
  function() {
    .Call(savvy_RArray_resolution__impl, `self`)
  }
}

`RArray_to_raster` <- function(self) {
  function() {
    .Call(savvy_RArray_to_raster__impl, `self`)
  }
}

`.savvy_wrap_RArray` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`epsg` <- `RArray_epsg`(ptr)
  e$`extent` <- `RArray_extent`(ptr)
  e$`names` <- `RArray_names`(ptr)
  e$`resolution` <- `RArray_resolution`(ptr)
  e$`to_raster` <- `RArray_to_raster`(ptr)

  class(e) <- c("rusterize::RArray", "RArray", "savvy_rusterize__sealed")
  e
}



`RArray` <- new.env(parent = emptyenv())

### associated functions for RArray



class(`RArray`) <- c("rusterize::RArray__bundle", "savvy_rusterize__sealed")

#' @export
`print.rusterize::RArray__bundle` <- function(x, ...) {
  cat('rusterize::RArray\n')
}

